
stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - node_modules/.bin/istanbul cover node_modules/.bin/_mocha tests
  dependencies:
    - build

