image: "node:alpine"

stages:
  - build
  - test
  - pages

build:
  stage: build
  script:
    - apk update
    # Rebuild leveldown
    - apk add make g++ python
    - npm install --build-from-source
    # Workarround htmltidy issue
    - apk add tidyhtml && cp $(which tidy) node_modules/htmltidy/bin/linux
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - apk update && apk add lsof
    - npm run test
  dependencies:
    - build

pages:
  stage: pages
  script:
    - npm run jsdoc
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - node
