set(ADD_FILES_COUNT "0")

function(add_info_files)
    MATH(EXPR ADD_FILES_COUNT "${ADD_FILES_COUNT} + 1")
    set(ADD_FILES_COUNT "${ADD_FILES_COUNT}" PARENT_SCOPE)
    set(_infofiles_target "_${CMAKE_CURRENT_LIST_FILE}-infofiles-noop-${ADD_FILES_COUNT}")
    string(REGEX REPLACE "[^a-zA-Z0-9]" "_" _infofiles_target "${_infofiles_target}")
    foreach(_it ${ARGN})
        if(NOT IS_DIRECTORY ${_it})
            set_source_files_properties(${_it} PROPERTIES HEADER_FILE_ONLY TRUE)
        endif()
    endforeach()
    add_custom_target(${_infofiles_target} SOURCES ${ARGN})
endfunction()
