macro(add_info_files)
    set(_infofiles_target "_${CMAKE_CURRENT_LIST_FILE}-infofiles-noop-${CMAKE_CURRENT_LIST_LINE}")
    string(REGEX REPLACE "[^a-zA-Z0-9]" "_" _infofiles_target "${_infofiles_target}")
    foreach(_it ${ARGN})
        if(NOT IS_DIRECTORY ${_it})
            set_source_files_properties(${_it} PROPERTIES HEADER_FILE_ONLY TRUE)
        endif()
    endforeach()
    add_custom_target(${_infofiles_target} SOURCES ${ARGN})
endmacro()
